name: production_deployment

on:
  push:
    tags:
      - v**-production

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Building application
        run: |
          npm run build

      - name: SSH to Server
        run: |
          mkdir ~/.ssh
          echo -e "${{ secrets.PRODUCTION_PRIVATE_KEY }}" > ~/.ssh/ssh-key
          chmod 400 ~/.ssh/ssh-key
          rsync -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/ssh-key" -r dist/* ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_HOST }}:${{ secrets.PRODUCTION_PATH }}
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ssh-key ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_HOST }} 'sudo systemctl restart nginx'
